### ISSUE TITLE
KeyError when importing Heusden dataset

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/hydxlib#47]
When importing this dataset [Heusden.hydx.zip](https://github.com/nens/hydxlib/files/10787365/Heusden.hydx.zip) to an empty 3Di sqlite, the following error is produced:

```
Traceback (most recent call last):
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\demo user/python/plugins\ThreeDiToolbox\processing\schematisation_algorithms.py", line 550, in processAlgorithm
run_import_export(export_type="threedi", hydx_path=hydx_path, out_path=out_path)
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\demo user\python\plugins\ThreeDiToolbox\deps\hydxlib\scripts.py", line 65, in run_import_export
export_threedi(hydx, out_path)File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\demo user\python\plugins\ThreeDiToolbox\deps\hydxlib\exporter.py", line 59, in export_threedi
commit_counts = write_threedi_to_db(threedi, threedi_db_settings)
File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\profiles\demo user\python\plugins\ThreeDiToolbox\deps\hydxlib\exporter.py", line 259, in write_threedi_to_db
imp_map["connection_node_id"] = connection_node_dict[imp_map["node.code"]]

KeyError: 'knp1'
```

**Comment by caspervdw** [comment]
Ik kan dit op zich wel repareren, maar te zien aan de logs heeft in dit bestand geen enkele Knooppunt een identificatiecode.

Nadere inspectie van het `Knooppunt.csv` bestand laat zien dat de headers in de verkeerde volgorde staan:

```
AAN_MVD;KNP_BRE;CMP_IDE;ITO_IDE;UNI_IDE;PUT_IDE;RST_IDE;INI_NIV;KNP_LEN;MVD_SCH;KNP_MAT;KNP_BOK;MVD_NIV;WOS_OPP;STA_OBJ;ALG_TOE;KNP_TYP;KNP_VRM;KNP_XCO;KNP_YCO;
knp1;"1000";;;;"3381";;;"1000";;"AG";"null";"2.6";;;"";"INS";"A";"143422.060";"412389.240";
```

De 1e kolom is "AAN_MVD" (aanname maaiveldhoogte) terwijl het duidelijk niet een maaiveldhoogte is, maar een identificatiecode die daar staat.

**Comment by leendertvanwolfswinkel** [comment]
OK dat lijkt me iets voor Rioned om naar te kijken; dan gaat er kennelijk iets mis in de vertaling van GWSW naar GWSW-Hyd
